# Form implementation generated from reading ui file 'mainpage.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QStatusBar


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(653, 242)
        self.widget = QtWidgets.QWidget(parent=Dialog)
        self.widget.setGeometry(QtCore.QRect(20, 10, 611, 221))
        self.widget.setObjectName("widget")
        self.verticalLayout_all_elements = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_all_elements.setContentsMargins(0, 0, 0, 20)
        self.verticalLayout_all_elements.setSpacing(50)
        self.verticalLayout_all_elements.setObjectName("verticalLayout_all_elements")
        self.Label_layout = QtWidgets.QGridLayout()
        self.Label_layout.setSpacing(100)
        self.Label_layout.setObjectName("Label_layout")
        self.label_registration = QtWidgets.QLabel(parent=self.widget)
        self.label_registration.setObjectName("label_registration")
        self.Label_layout.addWidget(self.label_registration, 0, 0, 1, 1)
        self.label_login = QtWidgets.QLabel(parent=self.widget)
        self.label_login.setObjectName("label_login")
        self.Label_layout.addWidget(self.label_login, 0, 1, 1, 1)
        self.verticalLayout_all_elements.addLayout(self.Label_layout)
        self.horizontal_linedit_layout = QtWidgets.QHBoxLayout()
        self.horizontal_linedit_layout.setSpacing(10)
        self.horizontal_linedit_layout.setObjectName("horizontal_linedit_layout")
        self.registration_layout = QtWidgets.QVBoxLayout()
        self.registration_layout.setObjectName("registration_layout")
        self.registration_name = QtWidgets.QLineEdit(parent=self.widget)
        self.registration_name.setObjectName("registration_name")
        self.registration_layout.addWidget(self.registration_name)
        self.registration_password = QtWidgets.QLineEdit(parent=self.widget)
        self.registration_password.setObjectName("registration_password")
        self.registration_layout.addWidget(self.registration_password)
        self.registration_retype_password = QtWidgets.QLineEdit(parent=self.widget)
        self.registration_retype_password.setObjectName("registration_retype_password")
        self.registration_layout.addWidget(self.registration_retype_password)
        self.registration_button = QtWidgets.QPushButton(parent=self.widget)
        self.registration_button.setObjectName("registration_button")
        self.registration_layout.addWidget(self.registration_button)
        self.horizontal_linedit_layout.addLayout(self.registration_layout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.login_name = QtWidgets.QLineEdit(parent=self.widget)
        self.login_name.setObjectName("login_name")
        self.verticalLayout_2.addWidget(self.login_name)
        self.login_password = QtWidgets.QLineEdit(parent=self.widget)
        self.login_password.setObjectName("login_password")
        self.verticalLayout_2.addWidget(self.login_password)
        self.login_button = QtWidgets.QPushButton(parent=self.widget)
        self.login_button.setObjectName("login_button")
        self.verticalLayout_2.addWidget(self.login_button)
        self.horizontal_linedit_layout.addLayout(self.verticalLayout_2)
        self.verticalLayout_all_elements.addLayout(self.horizontal_linedit_layout)
        self.verticalLayout_2.setSpacing(10)
        self.widget.update()
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_registration.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt;\">Регистрация</span></p></body></html>"))
        self.label_login.setText(_translate("Dialog", "<html><head/><body><p align=\"right\"><span style=\" font-size:16pt;\">Вход</span></p></body></html>"))
        self.registration_button.setText(_translate("Dialog", "Зарегистрироваться"))
        self.login_button.setText(_translate("Dialog", "Войти"))
